services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - backend-network
        volumes:
            - ./frontend:/app
            - /app/node_modules

    backend:
        image: shinsenter/symfony:php8.3-alpine
        ports:
            - 5000:80
        depends_on:
            - database
        networks:
            - backend-network
        volumes:
            - ./backend:/var/www/html

    database:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            - backend-network
        volumes:
            - db:/var/lib/postgresql/data

    adminer:
        build:
            context: ./adminer
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        depends_on:
            - database
        networks:
            - backend-network

    mailhog:
        image: mailhog/mailhog
        ports:
            - 8025:8025
        networks:
            - backend-network

networks:
    backend-network:

volumes:
    db:
