version: '3.8'

services:
    frontend:
        build:
            context: ..
            dockerfile: ./production/Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
        networks:
            - backend-network

    backend:
        image: shinsenter/symfony:php8.3-alpine
        ports:
            - 5000:80
        depends_on:
            - database
        networks:
            - backend-network
        volumes:
            - ./backend:/var/www/html # Vous pouvez enlever cette ligne si vous avez un Dockerfile pour backend

    database:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        networks:
            - backend-network
        volumes:
            - db:/var/lib/postgresql/data

networks:
    backend-network:

volumes:
    db:
