on:
    pull_request:
        branches: [trunk]

jobs:
    backend:
        name: Unit test backend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.2"
                  tools: phpstan, composer

            - name: Validate composer.json and composer.lock
              working-directory: ./backend
              run: composer validate

            - name: Get composer cache directory
              working-directory: ./backend
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              working-directory: ./backend
              run: composer install --prefer-dist

            - name: Run unit tests
              working-directory: ./backend
              run: composer test

    frontend:
        name: Unit test frontend
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-

            - name: Install dependencies
              working-directory: ./frontend
              run: npm install

            - name: Run unit tests
              working-directory: ./frontend
              run: npm test
